  - platform: ring

  - platform: mqtt
    name: "PS4 Power Status"
    unique_id: "PS4PowerStatus"
    state_topic: "nodered/ps4/power"
    value_template: "{%if is_state(entity_id,\"on\")-%}OFF{%-else-%}ON{%-endif%}" 

  - platform: mqtt
    name: "Front Hall MultiSensor Motion"
    unique_id: "Front Hall MultiSensor Motion"
    state_topic: "homeseer/Front_Hall/MultiSensor/Motion"
    device_class: motion
    payload_on: 255
    payload_off: 0

  - platform: mqtt
    name: "Family Room MultiSensor Motion"
    unique_id: "Family Room MultiSensor Motion"
    state_topic: "homeseer/Family_Room/MultiSensor/Motion"
    device_class: motion
    payload_on: 255
    payload_off: 0

# Sensor to Track if TV in FamilyRoom is on.
#  - platform: ping
#    name: FamilyRoomTV
#    host: !secret tv_ipaddy 
#    scan_interval: 120 

  - platform: workday
    country: CA
    province: "ON"

binary_sensor:
  - platform: hydrawise
