#  - platform: mqtt
#    name: "BackDoor Battery Level"
#    unique_id: "BackDoorBatteryLevel"
#    icon: mdi:battery
#    device_class: battery
#    unit_of_measurement: "%"
#    state_topic: homeseer/Back_Door/Door_Lock/Battery

  - platform: mqtt
    name: "FrontDoor Battery Level"
    unique_id: "FrontDoorBatteryLevel"
    icon: mdi:battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: homeeer/Front_Door/Door_Lock/Battery  

  - platform: mqtt
    name: "Front Door Lock Status"  
    unique_id: "FrontDoorLockStatus"
    state_topic: homeseer/Front_Door/Door_Lock/Notification_Status

# Homeseer Device ID 472 
  - platform: mqtt
    name: "Back Door Lock Status"  
    unique_id: "BackDoorLockStatus"
    state_topic: homeseer/Back_Door/Door_Lock/Notification_Status

  - platform: mqtt
    name: "Garage Overhead Lights Watts"
    unique_id: "GarageOverheadLightsWatts"
    icon: mdi:power-plug
    unit_of_measurement: "W"
    state_topic: homeseer/Garage/Garage_Overhead_Lights/Watts   

  - platform: mqtt
    name: "Garage Overhead Lights KWh"
    unique_id: "GarageOverheadLightsKWh"
    icon: mdi:power-plug
    unit_of_measurement: "KWh"
    state_topic: homeseer/Family_Room/Sasha_Phone_Smart_Switch/KWh

  - platform: mqtt
    name: "Front Hall MultiSensor Battery Level"
    unique_id: "FrontHallMultiSensorBatteryLevel"
    icon: mdi:battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: homeseer/Front_Hall/MultiSensor/Battery

  - platform: mqtt
    name: "Front Hall MultiSensor Temperature"
    unique_id: "FrontHallMultiSensorTemperature"
    device_class: temperature
    unit_of_measurement: "C"
    state_topic: homeseer/Front_Hall/MultiSensor/Temperature

  - platform: mqtt
    name: "Front Hall MultiSensor Light Level"
    unique_id: "FrontHallMultiSensorLightLevel"
    device_class: illuminance
    unit_of_measurement: "lx"
    state_topic: homeseer/Front_Hall/MultiSensor/LightLevel

  - platform: mqtt
    name: "Front Hall MultiSensor Relative Humidity"
    unique_id: "FrontHallMultiSensorRelativeHumidity"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: homeseer/Front_Hall/MultiSensor/Relative_Humidity

  - platform: mqtt
    name: "Family Room MultiSensor Battery Level"
    unique_id: "FamilyRoomMultiSensorBatteryLevel"
    icon: mdi:battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: homeseer/Family_Room/MultiSensor/Battery

  - platform: mqtt
    name: "Family Room MultiSensor Temperature"
    unique_id: "Family Room MultiSensorTemperature"
    device_class: temperature
    unit_of_measurement: "C"
    state_topic: homeseer/Family_Room/MultiSensor/Temperature

  - platform: mqtt
    name: "Family Room MultiSensor Light Level"
    unique_id: "Family Room MultiSensorLightLevel"
    device_class: illuminance
    unit_of_measurement: "lx"
    state_topic: homeseer/Family_Room/MultiSensor/LightLevel

  - platform: mqtt
    name: "Family Room MultiSensor Relative Humidity"
    unique_id: "FamilyRoomMultiSensorRelativeHumidity"
    device_class: humidity
    unit_of_measurement: "%"
    state_topic: homeseer/Family_Room/MultiSensor/Relative_Humidity

  - platform: filter
    name: "Filtered Realistic Front Hall Temperature"
    entity_id: sensor.front_hall_multiSensor_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

  - platform: min_max
    name: "Mean House Temperature"
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.mainfloor_thermostat_temperature
      - sensor.master_bedroom_thermostat_temperature
      - sensor.front_hall_multisensor_temperature

  - platform: mqtt
    name: "Sasha Bedroom Light Switch Battery Level"
    unique_id: "SashaLightSwitchatteryLevel"
    icon: mdi:battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: homeseer/Sasha_Room/Switch/Overhead_Light/Battery

  - platform: mqtt
    name: "PS4 Smart Switch Watts"
    unique_id: "BasementSmartSwitchWatts"
    icon: mdi:power-plug
    state_topic: "homeseer/Basement/PS4Smart_Switch/Watts"
    unit_of_measurement: "W"

  - platform: mqtt
    name: "Kristina Phone Charger Watts"
    unique_id: "KristinaPhoneChargerWatts"
    icon: mdi:power-plug
    state_topic: "homeseer/Garage/Switch/Workbench_Light/Watts"
    unit_of_measurement: "W"

#  - platform: mopar
#    username: paulm@spider.org
#    password: !secret mopar_password  
#    pin: !secret mopar_pin
  
  - platform: systemmonitor
    resources:
       - type: memory_free
       - type: memory_use_percent
       - type: load_1m
       - type: load_5m
       - type: load_15m
       - type: processor_use
       - type: network_in
         arg: eth0
       - type: network_out
         arg: eth0  
  
  - platform: travisci
    api_key: !secret github_token
    repository:
      - MyHomeAssistantConfig
    monitored_conditions:
      - last_build_state

  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
    monitored_conditions:
      - temperature
      - apparent_temperature
    scan_interval:
      days: 0
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0

# Homeseer node ID 313
  - platform: mqtt
    name: "Family Room Radiator Smart Switch KWh"
    unique_id: "FamilyRoomRadiatorSmartSwitchKwh"
    icon: mdi:power-plug
    unit_of_measurement: "KWh"
    state_topic: homeseer/Family_Room/Radiator/KWh    

# Homeseer node ID 314
  - platform: mqtt
    name: "Family Room Radiator Smart Switch Watts"
    unique_id: "FamilyRoomRadiatorSmartSwitchWatts"
    icon: mdi:power-plug
    unit_of_measurement: "Watts"
    state_topic: homeseer/Family_Room/Radiator/Watts    

# Homeseer node ID 315
  - platform: mqtt
    name: "Family Room Radiator Smart Switch Volts"
    unique_id: "FamilyRoomRadiatorSmartSwitchVolts"
    icon: mdi:power-plug
    unit_of_measurement: "Volts"
    state_topic: homeseer/Family_Room/Radiator/Volts

# Homeseer node ID 316
  - platform: mqtt
    name: "Family Room Radiator Smart Switch Amps"
    unique_id: "FamilyRoomRadiatorSmartSwitchAmps"
    icon: mdi:power-plug
    unit_of_measurement: "Amps"
    state_topic: homeseer/Family_Room/Radiator/Amps    

# Homeseer node ID 454
  - platform: mqtt
    name: "Master Bedroom Grow Light KWh"
    unique_id: "MasterBedroomGrowLightSmartSwitchKwh"
    icon: mdi:power-plug
    unit_of_measurement: "KWh"
    state_topic: homeseer/Master_Bedroom/Grow_Light_Smart_Switch/KWh    

# Homeseer node ID 455
  - platform: mqtt
    name: "Master Bedroom Grow Light Watts"
    unique_id: "MasterBedroomGrowLightSmartSwitchWatts"
    icon: mdi:power-plug
    unit_of_measurement: "Watts"
    state_topic: homeseer/Master_Bedroom/Grow_Light_Smart_Switch/Watts    

# Homeseer node ID 456
  - platform: mqtt
    name: "Master Bedroom Grow Light Volts"
    unique_id: "MasterBedroomGrowLightSmartSwitchVolts"
    icon: mdi:power-plug
    unit_of_measurement: "Volts"
    state_topic: homeseer/Master_Bedroom/Grow_Light_Smart_Switch/Volts

# Homeseer node ID 457
  - platform: mqtt
    name: "Master Bedroom Grow Light Volts"
    unique_id: "MasterBedroomGrowLightAmps"
    icon: mdi:power-plug
    unit_of_measurement: "Amps"
    state_topic: homeseer/Master_Bedroom/Grow_Light_Smart_Switch/Amps    

# What's the latest release on Docker Hub (eventually I'll automatically pull and run this)
  - platform: command_line
    name:  Home Assistant Latest Docker
    command:  curl -s -L https://registry.hub.docker.com/v2/repositories/homeassistant/home-assistant/tags/ | grep -Eo '"name":\s"[0-9.]*"' | head -1 | sed -e "s/\"name\":\s\"/${replace}/g" | sed -e "s/\"/${replace}/g"
    scan_interval: 28800      

    # Homeseer node ID 483
  - platform: mqtt
    name: "Pool Pump KWh"
    unique_id: "PoolPumpKwh"
    icon: mdi:power-plug
    unit_of_measurement: "KWh"
    state_topic: homeseer/Pool/Pump/KWh    

# Homeseer node ID 484
  - platform: mqtt
    name: "Pool Pump Watts"
    unique_id: "PoolPumpWatts"
    icon: mdi:power-plug
    unit_of_measurement: "Watts"
    state_topic: homeseer/Pool/Pump/Watts    

# Homeseer node ID 486
  - platform: mqtt
    name: "Pool Pump Amps"
    unique_id: "Pool Pump Amps"
    icon: mdi:power-plug
    unit_of_measurement: "Amps"
    state_topic: homeseer/Pool/Pump/Amp

# Homeseer node ID 503
  - platform: mqtt
    name: "Garage Storage Room Temperature"
    unique_id: "Garage Storge Temp"
    icon: mdi:thermometerlines
    unit_of_measurement: "Celcius"
    state_topic: homeseer/Garage/Storage/Temp  

# Homeseeri node ID 523
  - platform: mqtt
    name: "Garage Door Status"
    unique_id: "Garage Door Status"
    icon: mid:garage
    state_topic: homeseer/Garage/Status/Garage_Door_Status
    
 # Homeseeri node ID 523
  - platform: mqtt
    name: "Garage Motion"
    unique_id: "Garage Motion Sensor"
    icon: mid:garage
    state_topic: homeseer/Garage/Motion
    
binary_sensor:
  - platform: hydrawise

sensor:
  - platform: hydrawise
